import '../Widgets/LettersWidget.dart';

List<LettersWidget> mywidget = [
  LettersWidget(
    imagePicture: "images/letter1.png",
    letterName: "أ",
    letterExample1: "أرنب",
    letterExample2: "أسد",
    letterSoundEffect: "001-alif.mp3",
    example1Image: "images/ارنب.jpg",
    example2Image: "images/اسد.jpg",
  ),
  LettersWidget(
    imagePicture: "images/letter2.png",
    letterName: "ب",
    example1Image: "images/بطه.png",
    example2Image: "images/بقره.jpg",
    letterExample1: "بطه",
    letterExample2: "بقره",
    letterSoundEffect: "ba.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter3.png",
    letterName: "ت",
    example1Image: "images/تمساح.png",
    example2Image: "images/تفاحه.jpg",
    letterExample1: "تمساح",
    letterExample2: "تفاحه",
    letterSoundEffect: "003-taa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter4.png",
    letterName: "ث",
    example1Image: "images/ثعلب.jpg",
    example2Image: "images/ثعبان.jpg",
    letterExample1: "ثعلب",
    letterExample2: "ثعبان",
    letterSoundEffect: "004-tha.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter5.png",
    letterName: "ج",
    example1Image: "images/جرو.jpg",
    example2Image: "images/جمل.jpg",
    letterExample1: "جرو",
    letterExample2: "جمل",
    letterSoundEffect: "005-jeem.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter7.png",
    letterName: "ح",
    example1Image: "images/حريق.png",
    example2Image: "images/حمار.png",
    letterExample1: "حريق",
    letterExample2: "حمار",
    letterSoundEffect: "006-haa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter6.png",
    letterName: "خ",
    example1Image: "images/خنزير.jpg",
    example2Image: "images/خروف.jpg",
    letterExample1: "خنزير",
    letterExample2: "خروف",
    letterSoundEffect: "007-khaa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter8.png",
    letterName: "د",
    example1Image: "images/دب.png",
    example2Image: "images/دولفين.jpg",
    letterExample1: "دب",
    letterExample2: "دولفين",
    letterSoundEffect: "008-dal.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter9.png",
    letterName: "ذ",
    example1Image: "images/ذئب.jpg",
    example2Image: "images/ذبابه.jpg",
    letterExample1: "ذئب",
    letterExample2: "ذبابه",
    letterSoundEffect: "009-dhal.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter10.png",
    example1Image: "images/رمان.jpg",
    example2Image: "images/رجل.png",
    letterExample1: "رمان",
    letterExample2: "رجل",
    letterName: "ر",
    letterSoundEffect: "010-raa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter12.png",
    letterName: "ز",
    example1Image: "images/زرافه.jpg",
    example2Image: "images/زهره.png",
    letterExample1: "زرافه",
    letterExample2: "زهره",
    letterSoundEffect: "011-jaa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter11.png",
    letterName: "س",
    example1Image: "images/سله.jpg",
    example2Image: "images/سمكه.jpg",
    letterExample1: "سله",
    letterExample2: "سمكه",
    letterSoundEffect: "012-seen.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter13.png",
    letterName: "ش",
    example1Image: "images/شجره.jpg",
    example2Image: "images/شمام.jpg",
    letterExample1: "شجره",
    letterExample2: "شمام",
    letterSoundEffect: "013-sheen.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter14.png",
    letterName: "ص",
    example1Image: "images/صناره.png",
    example2Image: "images/صبار.jpg",
    letterExample1: "صناره",
    letterExample2: "صبار",
    letterSoundEffect: "014-saad.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter15.png",
    letterName: "ض",
    example1Image: "images/ضفضع.jpg",
    example2Image: "images/ضوء.jpg",
    letterExample1: "ضفضع",
    letterExample2: "ضوء",
    letterSoundEffect: "015-dhaad.mp3",
  ),
  LettersWidget(
    imagePicture: "images/ط.png",
    letterName: "ط",
    example1Image: "images/طائره.jpg",
    example2Image: "images/طاووس.png",
    letterExample1: "طائره",
    letterExample2: "طاووس",
    letterSoundEffect: "016-toa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter16.png",
    letterName: "ظ",
    example1Image: "images/ظبي.PNG",
    example2Image: "images/ظرف.PNG",
    letterExample1: "ظبي",
    letterExample2: "ظرف",
    letterSoundEffect: "017-dhaa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter17.png",
    letterName: "ع",
    example1Image: "images/عنب.jpg",
    example2Image: "images/عين.jpg",
    letterExample1: "عنب",
    letterExample2: "عين",
    letterSoundEffect: "018-ain.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter18.png",
    letterName: "غ",
    example1Image: "images/غراب.jpg",
    example2Image: "images/غوريلا.png",
    letterExample1: "غراب",
    letterExample2: "غوريلا",
    letterSoundEffect: "019-ghain.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter19.png",
    letterName: "ف",
    example1Image: "images/فراوله.jpg",
    example2Image: "images/فيل.png",
    letterExample1: "فراوله",
    letterExample2: "فيل",
    letterSoundEffect: "020-faa.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter20.png",
    letterName: "ق",
    example1Image: "images/قلب.png",
    example2Image: "images/قلم.png",
    letterExample1: "قلب",
    letterExample2: "قلم",
    letterSoundEffect: "021-qaaf.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter21.png",
    letterName: "ك",
    example1Image: "images/كره.jpg",
    example2Image: "images/كلب.jpg",
    letterExample1: "كره",
    letterExample2: "كلب",
    letterSoundEffect: "022-kaaf.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter22.png",
    letterName: "ل",
    example1Image: "images/لحم.jpg",
    example2Image: "images/ليمون.jpg",
    letterExample1: "لحم",
    letterExample2: "ليمون",
    letterSoundEffect: "023-laam.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter23.png",
    letterName: "م",
    example1Image: "images/مانجو.webp",
    example2Image: "images/مرآه.jpg",
    letterExample1: "مانجو",
    letterExample2: "مرآه",
    letterSoundEffect: "024-meem.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter24.png",
    letterName: "ن",
    example1Image: "images/نار.png",
    example2Image: "images/نمله.jpeg",
    letterExample1: "نار",
    letterExample2: "نمله",
    letterSoundEffect: "025-noon.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter25.png",
    letterName: "ة",
    example1Image: "images/هدهد.png",
    example2Image: "images/هرم.jpg",
    letterExample1: "هدهد",
    letterExample2: "هرم",
    letterSoundEffect: "027-ha.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter26.png",
    letterName: "و",
    example1Image: "images/ورده.jpg",
    example2Image: "images/ورقه.jpg",
    letterExample1: "ورده",
    letterExample2: "ورقه",
    letterSoundEffect: "026-waw.mp3",
  ),
  LettersWidget(
    imagePicture: "images/letter27.png",
    letterName: "ي",
    example1Image: "images/يد.png",
    example2Image: "images/يمامه.jpg",
    letterExample1: "يد",

    
    letterExample2: "يمامه",
    letterSoundEffect: "029-yaa.mp3",
  ),
];
